# Generated by Django 3.2.6 on 2022-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authers', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=300)),
                ('journal', models.CharField(max_length=300)),
            ],
        ),
    ]
